// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:amica/models/user_model.dart' as _i5;
import 'package:amica/models/user_profile_model.dart' as _i7;
import 'package:amica/services/auth_service.dart' as _i2;
import 'package:amica/services/user_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> register(
    String? username,
    String? displayName,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              username,
              displayName,
              email,
              password,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> verifyPin(String? tempId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [tempId, pin]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> setPin(String? pin, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setPin, [pin, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> removePin(
    String? currentPin,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removePin, [currentPin, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> resetPinByOtp(
    String? email,
    String? otp,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPinByOtp, [email, otp, newPin]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String?> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> fetchCurrentUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUser, [token]),
            returnValue: _i4.Future<_i5.User?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<Map<String, dynamic>> setPassword(
    String? password,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setPassword, [password, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> sendPasswordResetCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetCode, [email]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> verifyResetCode(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [email, code]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> resetPasswordFinish(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordFinish, [email, code, newPassword]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i6.UserService {
  @override
  _i4.Future<_i7.UserProfileData?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i7.UserProfileData?>.value(),
            returnValueForMissingStub: _i4.Future<_i7.UserProfileData?>.value(),
          )
          as _i4.Future<_i7.UserProfileData?>);

  @override
  _i4.Future<bool> followUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [userId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> updateProfile({
    required String? displayName,
    required String? username,
    required String? bio,
    _i8.File? avatarFile,
    _i8.File? bannerFile,
    String? practiceAddress,
    String? practiceSchedule,
    String? province,
    bool? isProfessional = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #username: username,
              #bio: bio,
              #avatarFile: avatarFile,
              #bannerFile: bannerFile,
              #practiceAddress: practiceAddress,
              #practiceSchedule: practiceSchedule,
              #province: province,
              #isProfessional: isProfessional,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> applyVerification({
    required String? fullName,
    required String? strNumber,
    required String? province,
    required String? address,
    required String? schedule,
    required _i8.File? strImage,
    required _i8.File? ktpImage,
    required _i8.File? selfieImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyVerification, [], {
              #fullName: fullName,
              #strNumber: strNumber,
              #province: province,
              #address: address,
              #schedule: schedule,
              #strImage: strImage,
              #ktpImage: ktpImage,
              #selfieImage: selfieImage,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSavedPosts(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPosts, [targetUserId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> updateSavedPrivacy(bool? isPublic) =>
      (super.noSuchMethod(
            Invocation.method(#updateSavedPrivacy, [isPublic]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateDeviceId(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeviceId, [playerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> changePassword(String? oldPass, String? newPass) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [oldPass, newPass]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> changeEmail(String? newEmail, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [newEmail, password]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<_i5.User>> getBlockedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedUsers, []),
            returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.User>>.value(
              <_i5.User>[],
            ),
          )
          as _i4.Future<List<_i5.User>>);

  @override
  _i4.Future<bool> unblockUser(String? targetId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [targetId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> blockUser(String? targetId) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [targetId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> sendFeedback(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendFeedback, [text]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getFollowers(
    String? userId,
    int? page,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userId, page, query]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getFollowing(
    String? userId,
    int? page,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [userId, page, query]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> updateModerationSetting(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#updateModerationSetting, [enabled]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
