// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/providers/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:amica/models/user_model.dart' as _i7;
import 'package:amica/services/chat_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:socket_io_client/src/engine/socket.dart' as _i11;
import 'package:socket_io_client/src/manager.dart' as _i2;
import 'package:socket_io_client/src/socket.dart' as _i3;
import 'package:socket_io_common/src/parser/parser.dart' as _i4;
import 'package:socket_io_common/src/util/event_emitter.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeManager_0 extends _i1.SmartFake implements _i2.Manager {
  _FakeManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocket_1 extends _i1.SmartFake implements _i3.Socket {
  _FakeSocket_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncoder_2 extends _i1.SmartFake implements _i4.Encoder {
  _FakeEncoder_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDecoder_3 extends _i1.SmartFake implements _i4.Decoder {
  _FakeDecoder_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i5.ChatService {
  @override
  _i6.Future<Map<String, dynamic>> getOrCreateChat(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateChat, [targetUserId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i7.User>> getMutualFriends(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getMutualFriends, [query]),
            returnValue: _i6.Future<List<_i7.User>>.value(<_i7.User>[]),
            returnValueForMissingStub: _i6.Future<List<_i7.User>>.value(
              <_i7.User>[],
            ),
          )
          as _i6.Future<List<_i7.User>>);

  @override
  _i6.Future<Map<String, dynamic>> createGroup(
    String? name,
    _i8.File? image,
    List<String>? memberIds,
    bool? allowInvites,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [
              name,
              image,
              memberIds,
              allowInvites,
            ]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> leaveGroup(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGroup, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#clearChat, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessage(String? msgId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [msgId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<dynamic>> getBannedList(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getBannedList, [chatId]),
            returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i6.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<void> unbanUser(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unbanUser, [chatId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getGroupDetails(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupDetails, [chatId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> updateGroupInfo(
    String? chatId,
    String? name,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupInfo, [chatId, name, imagePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> addMembers(
    String? chatId,
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMembers, [chatId, userIds]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> kickMember(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#kickMember, [chatId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> banMember(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#banMember, [chatId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setMemberRole(
    String? chatId,
    String? userId,
    String? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setMemberRole, [chatId, userId, role]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> generateInviteLink(String? chatId, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#generateInviteLink, [chatId, type]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateInviteLink, [chatId, type]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateInviteLink, [chatId, type]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> updateGroupSettings(String? chatId, bool? allowInvites) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupSettings, [chatId, allowInvites]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<dynamic>> getActiveInvites(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveInvites, [chatId]),
            returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i6.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<void> revokeInvite(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#revokeInvite, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getInviteInfo(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getInviteInfo, [token]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getGroupPreview(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupPreview, [chatId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> joinGroup(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#joinGroup, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> deleteConversationPermanently(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationPermanently, [chatId]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> markDeliveredBackground(String? msgId) =>
      (super.noSuchMethod(
            Invocation.method(#markDeliveredBackground, [msgId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [Socket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocket extends _i1.Mock implements _i3.Socket {
  @override
  _i2.Manager get io =>
      (super.noSuchMethod(
            Invocation.getter(#io),
            returnValue: _FakeManager_0(this, Invocation.getter(#io)),
            returnValueForMissingStub: _FakeManager_0(
              this,
              Invocation.getter(#io),
            ),
          )
          as _i2.Manager);

  @override
  bool get connected =>
      (super.noSuchMethod(
            Invocation.getter(#connected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get recovered =>
      (super.noSuchMethod(
            Invocation.getter(#recovered),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<dynamic> get receiveBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#receiveBuffer),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> get sendBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#sendBuffer),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  String get nsp =>
      (super.noSuchMethod(
            Invocation.getter(#nsp),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#nsp)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#nsp),
            ),
          )
          as String);

  @override
  num get ids =>
      (super.noSuchMethod(
            Invocation.getter(#ids),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as num);

  @override
  Map<dynamic, dynamic> get acks =>
      (super.noSuchMethod(
            Invocation.getter(#acks),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  Map<dynamic, dynamic> get flags =>
      (super.noSuchMethod(
            Invocation.getter(#flags),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  bool get disconnected =>
      (super.noSuchMethod(
            Invocation.getter(#disconnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get active =>
      (super.noSuchMethod(
            Invocation.getter(#active),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Socket get volatile =>
      (super.noSuchMethod(
            Invocation.getter(#volatile),
            returnValue: _FakeSocket_1(this, Invocation.getter(#volatile)),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.getter(#volatile),
            ),
          )
          as _i3.Socket);

  @override
  set io(_i2.Manager? value) => super.noSuchMethod(
    Invocation.setter(#io, value),
    returnValueForMissingStub: null,
  );

  @override
  set id(String? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set connected(bool? value) => super.noSuchMethod(
    Invocation.setter(#connected, value),
    returnValueForMissingStub: null,
  );

  @override
  set recovered(bool? value) => super.noSuchMethod(
    Invocation.setter(#recovered, value),
    returnValueForMissingStub: null,
  );

  @override
  set auth(dynamic value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set receiveBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#receiveBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#sendBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set nsp(String? value) => super.noSuchMethod(
    Invocation.setter(#nsp, value),
    returnValueForMissingStub: null,
  );

  @override
  set ids(num? value) => super.noSuchMethod(
    Invocation.setter(#ids, value),
    returnValueForMissingStub: null,
  );

  @override
  set acks(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#acks, value),
    returnValueForMissingStub: null,
  );

  @override
  set subs(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#subs, value),
    returnValueForMissingStub: null,
  );

  @override
  set flags(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#flags, value),
    returnValueForMissingStub: null,
  );

  @override
  set query(String? value) => super.noSuchMethod(
    Invocation.setter(#query, value),
    returnValueForMissingStub: null,
  );

  @override
  void subEvents() => super.noSuchMethod(
    Invocation.method(#subEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Socket open() =>
      (super.noSuchMethod(
            Invocation.method(#open, []),
            returnValue: _FakeSocket_1(this, Invocation.method(#open, [])),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#open, []),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _FakeSocket_1(this, Invocation.method(#connect, [])),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#connect, []),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket send(List<dynamic>? args) =>
      (super.noSuchMethod(
            Invocation.method(#send, [args]),
            returnValue: _FakeSocket_1(this, Invocation.method(#send, [args])),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#send, [args]),
            ),
          )
          as _i3.Socket);

  @override
  void emit(String? event, [dynamic data]) => super.noSuchMethod(
    Invocation.method(#emit, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  void emitWithAck(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitWithAck,
      [event, data],
      {#ack: ack, #binary: binary},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<dynamic> emitWithAckAsync(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #emitWithAckAsync,
              [event, data],
              {#ack: ack, #binary: binary},
            ),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  void notifyOutgoingListeners(Map<dynamic, dynamic>? packet) =>
      super.noSuchMethod(
        Invocation.method(#notifyOutgoingListeners, [packet]),
        returnValueForMissingStub: null,
      );

  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#packet, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onopen([dynamic _0]) => super.noSuchMethod(
    Invocation.method(#onopen, [_0]),
    returnValueForMissingStub: null,
  );

  @override
  void sendConnectPacket(Map<dynamic, dynamic>? data) => super.noSuchMethod(
    Invocation.method(#sendConnectPacket, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void onerror(dynamic err) => super.noSuchMethod(
    Invocation.method(#onerror, [err]),
    returnValueForMissingStub: null,
  );

  @override
  void onclose(dynamic reason) => super.noSuchMethod(
    Invocation.method(#onclose, [reason]),
    returnValueForMissingStub: null,
  );

  @override
  void onpacket(dynamic packet) => super.noSuchMethod(
    Invocation.method(#onpacket, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onevent(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#onevent, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void emitEvent(List<dynamic>? args) => super.noSuchMethod(
    Invocation.method(#emitEvent, [args]),
    returnValueForMissingStub: null,
  );

  @override
  Function ack(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#ack, [id]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as Function);

  @override
  void onack(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#onack, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onconnect(dynamic id, dynamic pid) => super.noSuchMethod(
    Invocation.method(#onconnect, [id, pid]),
    returnValueForMissingStub: null,
  );

  @override
  void emitBuffered() => super.noSuchMethod(
    Invocation.method(#emitBuffered, []),
    returnValueForMissingStub: null,
  );

  @override
  void ondisconnect() => super.noSuchMethod(
    Invocation.method(#ondisconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void destroy() => super.noSuchMethod(
    Invocation.method(#destroy, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Socket close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _FakeSocket_1(this, Invocation.method(#close, [])),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#close, []),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#disconnect, []),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#disconnect, []),
            ),
          )
          as _i3.Socket);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Socket compress(dynamic compress) =>
      (super.noSuchMethod(
            Invocation.method(#compress, [compress]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#compress, [compress]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#compress, [compress]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket timeout(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeout]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#timeout, [timeout]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#timeout, [timeout]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket onAny(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#onAny, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#onAny, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#onAny, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket prependAny(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#prependAny, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#prependAny, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#prependAny, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket offAny([_i10.AnyEventHandler<dynamic>? handler]) =>
      (super.noSuchMethod(
            Invocation.method(#offAny, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#offAny, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#offAny, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  List<dynamic> listenersAny() =>
      (super.noSuchMethod(
            Invocation.method(#listenersAny, []),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  _i3.Socket onAnyOutgoing(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#onAnyOutgoing, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#onAnyOutgoing, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#onAnyOutgoing, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket prependAnyOutgoing(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#prependAnyOutgoing, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#prependAnyOutgoing, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#prependAnyOutgoing, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  _i3.Socket offAnyOutgoing([_i10.AnyEventHandler<dynamic>? handler]) =>
      (super.noSuchMethod(
            Invocation.method(#offAnyOutgoing, [handler]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#offAnyOutgoing, [handler]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#offAnyOutgoing, [handler]),
            ),
          )
          as _i3.Socket);

  @override
  List<dynamic> listenersAnyOutgoing() =>
      (super.noSuchMethod(
            Invocation.method(#listenersAnyOutgoing, []),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  void emitReserved(dynamic event, [dynamic data]) => super.noSuchMethod(
    Invocation.method(#emitReserved, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic Function() on(String? event, _i10.EventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#on, [event, handler]),
            returnValue: () => null,
            returnValueForMissingStub: () => null,
          )
          as dynamic Function());

  @override
  void once(String? event, _i10.EventHandler<dynamic>? handler) =>
      super.noSuchMethod(
        Invocation.method(#once, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void off(String? event, [_i10.EventHandler<dynamic>? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  bool hasListeners(String? event) =>
      (super.noSuchMethod(
            Invocation.method(#hasListeners, [event]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [Manager].
///
/// See the documentation for Mockito's code generation for more information.
class MockManager extends _i1.Mock implements _i2.Manager {
  @override
  Map<String, _i3.Socket> get nsps =>
      (super.noSuchMethod(
            Invocation.getter(#nsps),
            returnValue: <String, _i3.Socket>{},
            returnValueForMissingStub: <String, _i3.Socket>{},
          )
          as Map<String, _i3.Socket>);

  @override
  List<dynamic> get subs =>
      (super.noSuchMethod(
            Invocation.getter(#subs),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as List<dynamic>);

  @override
  String get readyState =>
      (super.noSuchMethod(
            Invocation.getter(#readyState),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#readyState),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#readyState),
            ),
          )
          as String);

  @override
  String get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#uri),
            ),
          )
          as String);

  @override
  bool get reconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#reconnecting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Encoder get encoder =>
      (super.noSuchMethod(
            Invocation.getter(#encoder),
            returnValue: _FakeEncoder_2(this, Invocation.getter(#encoder)),
            returnValueForMissingStub: _FakeEncoder_2(
              this,
              Invocation.getter(#encoder),
            ),
          )
          as _i4.Encoder);

  @override
  _i4.Decoder get decoder =>
      (super.noSuchMethod(
            Invocation.getter(#decoder),
            returnValue: _FakeDecoder_3(this, Invocation.getter(#decoder)),
            returnValueForMissingStub: _FakeDecoder_3(
              this,
              Invocation.getter(#decoder),
            ),
          )
          as _i4.Decoder);

  @override
  bool get autoConnect =>
      (super.noSuchMethod(
            Invocation.getter(#autoConnect),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set nsps(Map<String, _i3.Socket>? value) => super.noSuchMethod(
    Invocation.setter(#nsps, value),
    returnValueForMissingStub: null,
  );

  @override
  set subs(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#subs, value),
    returnValueForMissingStub: null,
  );

  @override
  set options(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#reconnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectionAttempts(num? value) => super.noSuchMethod(
    Invocation.setter(#reconnectionAttempts, value),
    returnValueForMissingStub: null,
  );

  @override
  set timeout(num? value) => super.noSuchMethod(
    Invocation.setter(#timeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set readyState(String? value) => super.noSuchMethod(
    Invocation.setter(#readyState, value),
    returnValueForMissingStub: null,
  );

  @override
  set uri(String? value) => super.noSuchMethod(
    Invocation.setter(#uri, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnecting(bool? value) => super.noSuchMethod(
    Invocation.setter(#reconnecting, value),
    returnValueForMissingStub: null,
  );

  @override
  set engine(_i11.Socket? value) => super.noSuchMethod(
    Invocation.setter(#engine, value),
    returnValueForMissingStub: null,
  );

  @override
  set encoder(_i4.Encoder? value) => super.noSuchMethod(
    Invocation.setter(#encoder, value),
    returnValueForMissingStub: null,
  );

  @override
  set decoder(_i4.Decoder? value) => super.noSuchMethod(
    Invocation.setter(#decoder, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoConnect(bool? value) => super.noSuchMethod(
    Invocation.setter(#autoConnect, value),
    returnValueForMissingStub: null,
  );

  @override
  set skipReconnect(bool? value) => super.noSuchMethod(
    Invocation.setter(#skipReconnect, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectionDelay(num? v) => super.noSuchMethod(
    Invocation.setter(#reconnectionDelay, v),
    returnValueForMissingStub: null,
  );

  @override
  set randomizationFactor(num? v) => super.noSuchMethod(
    Invocation.setter(#randomizationFactor, v),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectionDelayMax(num? v) => super.noSuchMethod(
    Invocation.setter(#reconnectionDelayMax, v),
    returnValueForMissingStub: null,
  );

  @override
  void maybeReconnectOnOpen() => super.noSuchMethod(
    Invocation.method(#maybeReconnectOnOpen, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Manager open({dynamic callback, Map<dynamic, dynamic>? opts}) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#callback: callback, #opts: opts}),
            returnValue: _FakeManager_0(
              this,
              Invocation.method(#open, [], {#callback: callback, #opts: opts}),
            ),
            returnValueForMissingStub: _FakeManager_0(
              this,
              Invocation.method(#open, [], {#callback: callback, #opts: opts}),
            ),
          )
          as _i2.Manager);

  @override
  _i2.Manager connect({dynamic callback, Map<dynamic, dynamic>? opts}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {#callback: callback, #opts: opts}),
            returnValue: _FakeManager_0(
              this,
              Invocation.method(#connect, [], {
                #callback: callback,
                #opts: opts,
              }),
            ),
            returnValueForMissingStub: _FakeManager_0(
              this,
              Invocation.method(#connect, [], {
                #callback: callback,
                #opts: opts,
              }),
            ),
          )
          as _i2.Manager);

  @override
  void onopen([dynamic _0]) => super.noSuchMethod(
    Invocation.method(#onopen, [_0]),
    returnValueForMissingStub: null,
  );

  @override
  void onping([dynamic _0]) => super.noSuchMethod(
    Invocation.method(#onping, [_0]),
    returnValueForMissingStub: null,
  );

  @override
  void ondata(dynamic data) => super.noSuchMethod(
    Invocation.method(#ondata, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void ondecoded(dynamic packet) => super.noSuchMethod(
    Invocation.method(#ondecoded, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onerror(dynamic err) => super.noSuchMethod(
    Invocation.method(#onerror, [err]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Socket socket(String? nsp, Map<dynamic, dynamic>? opts) =>
      (super.noSuchMethod(
            Invocation.method(#socket, [nsp, opts]),
            returnValue: _FakeSocket_1(
              this,
              Invocation.method(#socket, [nsp, opts]),
            ),
            returnValueForMissingStub: _FakeSocket_1(
              this,
              Invocation.method(#socket, [nsp, opts]),
            ),
          )
          as _i3.Socket);

  @override
  void destroy(dynamic socket) => super.noSuchMethod(
    Invocation.method(#destroy, [socket]),
    returnValueForMissingStub: null,
  );

  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#packet, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void cleanup() => super.noSuchMethod(
    Invocation.method(#cleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void onclose(dynamic error) => super.noSuchMethod(
    Invocation.method(#onclose, [error]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Manager reconnect() =>
      (super.noSuchMethod(
            Invocation.method(#reconnect, []),
            returnValue: _FakeManager_0(
              this,
              Invocation.method(#reconnect, []),
            ),
            returnValueForMissingStub: _FakeManager_0(
              this,
              Invocation.method(#reconnect, []),
            ),
          )
          as _i2.Manager);

  @override
  void onreconnect() => super.noSuchMethod(
    Invocation.method(#onreconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(String? event, [dynamic data]) => super.noSuchMethod(
    Invocation.method(#emit, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  void emitReserved(dynamic event, [dynamic data]) => super.noSuchMethod(
    Invocation.method(#emitReserved, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic Function() on(String? event, _i10.EventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
            Invocation.method(#on, [event, handler]),
            returnValue: () => null,
            returnValueForMissingStub: () => null,
          )
          as dynamic Function());

  @override
  void once(String? event, _i10.EventHandler<dynamic>? handler) =>
      super.noSuchMethod(
        Invocation.method(#once, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void onAny(_i10.AnyEventHandler<dynamic>? handler) => super.noSuchMethod(
    Invocation.method(#onAny, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void off(String? event, [_i10.EventHandler<dynamic>? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offAny([_i10.AnyEventHandler<dynamic>? handler]) => super.noSuchMethod(
    Invocation.method(#offAny, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  bool hasListeners(String? event) =>
      (super.noSuchMethod(
            Invocation.method(#hasListeners, [event]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
