// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/providers/profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:amica/models/post_model.dart' as _i8;
import 'package:amica/models/user_model.dart' as _i6;
import 'package:amica/models/user_profile_model.dart' as _i4;
import 'package:amica/services/post_service.dart' as _i7;
import 'package:amica/services/user_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  @override
  _i3.Future<_i4.UserProfileData?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i3.Future<_i4.UserProfileData?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.UserProfileData?>.value(),
          )
          as _i3.Future<_i4.UserProfileData?>);

  @override
  _i3.Future<bool> followUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> updateProfile({
    required String? displayName,
    required String? username,
    required String? bio,
    _i5.File? avatarFile,
    _i5.File? bannerFile,
    String? practiceAddress,
    String? practiceSchedule,
    String? province,
    bool? isProfessional = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #username: username,
              #bio: bio,
              #avatarFile: avatarFile,
              #bannerFile: bannerFile,
              #practiceAddress: practiceAddress,
              #practiceSchedule: practiceSchedule,
              #province: province,
              #isProfessional: isProfessional,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> applyVerification({
    required String? fullName,
    required String? strNumber,
    required String? province,
    required String? address,
    required String? schedule,
    required _i5.File? strImage,
    required _i5.File? ktpImage,
    required _i5.File? selfieImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyVerification, [], {
              #fullName: fullName,
              #strNumber: strNumber,
              #province: province,
              #address: address,
              #schedule: schedule,
              #strImage: strImage,
              #ktpImage: ktpImage,
              #selfieImage: selfieImage,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getSavedPosts(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPosts, [targetUserId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> updateSavedPrivacy(bool? isPublic) =>
      (super.noSuchMethod(
            Invocation.method(#updateSavedPrivacy, [isPublic]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateDeviceId(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeviceId, [playerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> changePassword(String? oldPass, String? newPass) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [oldPass, newPass]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> changeEmail(String? newEmail, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [newEmail, password]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<List<_i6.User>> getBlockedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedUsers, []),
            returnValue: _i3.Future<List<_i6.User>>.value(<_i6.User>[]),
            returnValueForMissingStub: _i3.Future<List<_i6.User>>.value(
              <_i6.User>[],
            ),
          )
          as _i3.Future<List<_i6.User>>);

  @override
  _i3.Future<bool> unblockUser(String? targetId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [targetId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> blockUser(String? targetId) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [targetId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> sendFeedback(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendFeedback, [text]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getFollowers(
    String? userId,
    int? page,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userId, page, query]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getFollowing(
    String? userId,
    int? page,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [userId, page, query]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> updateModerationSetting(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#updateModerationSetting, [enabled]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i7.PostService {
  @override
  _i3.Future<Map<String, dynamic>> getPosts({
    int? page = 1,
    int? perPage = 10,
    String? userId,
    String? filter = 'latest',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #page: page,
              #perPage: perPage,
              #userId: userId,
              #filter: filter,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<_i8.Post?> getPostById(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i3.Future<_i8.Post?>.value(),
            returnValueForMissingStub: _i3.Future<_i8.Post?>.value(),
          )
          as _i3.Future<_i8.Post?>);

  @override
  _i3.Future<bool> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleSave(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSave, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> createPost({
    required String? caption,
    required List<String>? tags,
    _i5.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #caption: caption,
              #tags: tags,
              #imageFile: imageFile,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i8.Post>> getMyModerationPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getMyModerationPosts, []),
            returnValue: _i3.Future<List<_i8.Post>>.value(<_i8.Post>[]),
            returnValueForMissingStub: _i3.Future<List<_i8.Post>>.value(
              <_i8.Post>[],
            ),
          )
          as _i3.Future<List<_i8.Post>>);

  @override
  _i3.Future<Map<String, dynamic>> submitAppeal(
    String? postId,
    String? justification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitAppeal, [postId, justification]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> acknowledgeRejection(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeRejection, [postId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
