// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/providers/sdq_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:amica/models/sdq_model.dart' as _i2;
import 'package:amica/services/sdq_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSdqFullResult_0 extends _i1.SmartFake implements _i2.SdqFullResult {
  _FakeSdqFullResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SdqService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSdqService extends _i1.Mock implements _i3.SdqService {
  @override
  _i4.Future<_i2.SdqFullResult> submitAnswers(List<int>? answers) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnswers, [answers]),
            returnValue: _i4.Future<_i2.SdqFullResult>.value(
              _FakeSdqFullResult_0(
                this,
                Invocation.method(#submitAnswers, [answers]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SdqFullResult>.value(
              _FakeSdqFullResult_0(
                this,
                Invocation.method(#submitAnswers, [answers]),
              ),
            ),
          )
          as _i4.Future<_i2.SdqFullResult>);

  @override
  _i4.Future<List<_i2.SdqHistoryItem>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i4.Future<List<_i2.SdqHistoryItem>>.value(
              <_i2.SdqHistoryItem>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i2.SdqHistoryItem>>.value(
                  <_i2.SdqHistoryItem>[],
                ),
          )
          as _i4.Future<List<_i2.SdqHistoryItem>>);

  @override
  _i4.Future<_i2.SdqFullResult> getResultDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getResultDetail, [id]),
            returnValue: _i4.Future<_i2.SdqFullResult>.value(
              _FakeSdqFullResult_0(
                this,
                Invocation.method(#getResultDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SdqFullResult>.value(
              _FakeSdqFullResult_0(
                this,
                Invocation.method(#getResultDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.SdqFullResult>);
}
