// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/widgets/post_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:amica/models/post_model.dart' as _i3;
import 'package:amica/models/user_model.dart' as _i9;
import 'package:amica/provider/auth_provider.dart' as _i8;
import 'package:amica/provider/navigation_provider.dart' as _i11;
import 'package:amica/provider/post_provider.dart' as _i2;
import 'package:amica/provider/profile_provider.dart' as _i10;
import 'package:flutter/material.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostProvider extends _i1.Mock implements _i2.PostProvider {
  @override
  List<_i3.Post> get posts =>
      (super.noSuchMethod(
            Invocation.getter(#posts),
            returnValue: <_i3.Post>[],
            returnValueForMissingStub: <_i3.Post>[],
          )
          as List<_i3.Post>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasMore =>
      (super.noSuchMethod(
            Invocation.getter(#hasMore),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isUploading =>
      (super.noSuchMethod(
            Invocation.getter(#isUploading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get currentFilter =>
      (super.noSuchMethod(
            Invocation.getter(#currentFilter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currentFilter),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currentFilter),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setFilter(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#setFilter, [filter]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearModerationError() => super.noSuchMethod(
    Invocation.method(#clearModerationError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> refreshPosts() =>
      (super.noSuchMethod(
            Invocation.method(#refreshPosts, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPosts, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleLike(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleSave(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSave, [postId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void incrementCommentCount(String? postId) => super.noSuchMethod(
    Invocation.method(#incrementCommentCount, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  void decrementCommentCount(String? postId) => super.noSuchMethod(
    Invocation.method(#decrementCommentCount, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Map<String, dynamic>> createPost({
    required String? caption,
    required List<String>? tags,
    _i6.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #caption: caption,
              #tags: tags,
              #imageFile: imageFile,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFollowFromFeed(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFollowFromFeed, [targetUserId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Post?> getPostById(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i5.Future<_i3.Post?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.Post?>.value(),
          )
          as _i5.Future<_i3.Post?>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get needsPasswordSet =>
      (super.noSuchMethod(
            Invocation.getter(#needsPasswordSet),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String> get blockedUserIds =>
      (super.noSuchMethod(
            Invocation.getter(#blockedUserIds),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> loadBlockedUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#loadBlockedUserIds, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void updateUser(_i9.User? newUser) => super.noSuchMethod(
    Invocation.method(#updateUser, [newUser]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String?> getFreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFreshToken, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> register(
    String? username,
    String? displayName,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              username,
              displayName,
              email,
              password,
            ]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, dynamic>> attemptLogin(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#attemptLogin, [email, password]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String?> verifyPinLogin(String? tempId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPinLogin, [tempId, pin]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> setPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setPin, [pin]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> removePin(String? currentPin) =>
      (super.noSuchMethod(
            Invocation.method(#removePin, [currentPin]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> resetPinByOtp(
    String? email,
    String? otp,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPinByOtp, [email, otp, newPin]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> setPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#setPassword, [password]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> completePasswordSetup() =>
      (super.noSuchMethod(
            Invocation.method(#completePasswordSetup, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> sendResetCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetCode, [email]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> verifyResetCode(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [email, code]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> resetPasswordFinish(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordFinish, [email, code, newPassword]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> toggleModeration(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleModeration, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> performLogout() =>
      (super.noSuchMethod(
            Invocation.method(#performLogout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileProvider extends _i1.Mock implements _i10.ProfileProvider {
  @override
  bool get isLoadingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingProfile),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoadingPosts =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingPosts),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.Post> get imagePosts =>
      (super.noSuchMethod(
            Invocation.getter(#imagePosts),
            returnValue: <_i3.Post>[],
            returnValueForMissingStub: <_i3.Post>[],
          )
          as List<_i3.Post>);

  @override
  List<_i3.Post> get textPosts =>
      (super.noSuchMethod(
            Invocation.getter(#textPosts),
            returnValue: <_i3.Post>[],
            returnValueForMissingStub: <_i3.Post>[],
          )
          as List<_i3.Post>);

  @override
  bool get hasMorePosts =>
      (super.noSuchMethod(
            Invocation.getter(#hasMorePosts),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.Post> get savedPosts =>
      (super.noSuchMethod(
            Invocation.getter(#savedPosts),
            returnValue: <_i3.Post>[],
            returnValueForMissingStub: <_i3.Post>[],
          )
          as List<_i3.Post>);

  @override
  bool get isLoadingSaved =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingSaved),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSavedCollectionPrivate =>
      (super.noSuchMethod(
            Invocation.getter(#isSavedCollectionPrivate),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get myPrivacySetting =>
      (super.noSuchMethod(
            Invocation.getter(#myPrivacySetting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set errorMessage(String? msg) => super.noSuchMethod(
    Invocation.setter(#errorMessage, msg),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> loadFullProfile(String? userId, {String? currentUserId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadFullProfile,
              [userId],
              {#currentUserId: currentUserId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadSavedPosts(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedPosts, [targetUserId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> togglePrivacySetting(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#togglePrivacySetting, [value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void toggleLikeLocal(String? postId) => super.noSuchMethod(
    Invocation.method(#toggleLikeLocal, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSaveLocal(String? postId) => super.noSuchMethod(
    Invocation.method(#toggleSaveLocal, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadMorePosts() =>
      (super.noSuchMethod(
            Invocation.method(#loadMorePosts, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshProfile({
    String? currentUserId,
    String? targetUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, [], {
              #currentUserId: currentUserId,
              #targetUserId: targetUserId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFollow() =>
      (super.noSuchMethod(
            Invocation.method(#toggleFollow, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i11.NavigationProvider {
  @override
  int get selectedIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setIndex(int? index) => super.noSuchMethod(
    Invocation.method(#setIndex, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i12.NavigatorObserver {
  @override
  void didPush(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i12.Route<dynamic>? route, _i12.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i12.Route<dynamic>? newRoute,
    _i12.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i12.Route<dynamic>? topRoute,
    _i12.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
