// Mocks generated by Mockito 5.4.6 from annotations
// in amica/test/pages/mainpage/chat_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:ui' as _i9;

import 'package:amica/models/chat_model.dart' as _i3;
import 'package:amica/models/messages_model.dart' as _i5;
import 'package:amica/models/user_model.dart' as _i8;
import 'package:amica/provider/auth_provider.dart' as _i10;
import 'package:amica/provider/chat_provider.dart' as _i2;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:socket_io_client/socket_io_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatProvider extends _i1.Mock implements _i2.ChatProvider {
  @override
  List<_i3.ChatRoom> get inbox =>
      (super.noSuchMethod(
            Invocation.getter(#inbox),
            returnValue: <_i3.ChatRoom>[],
            returnValueForMissingStub: <_i3.ChatRoom>[],
          )
          as List<_i3.ChatRoom>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get unreadMessageCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadMessageCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set socket(_i4.Socket? value) => super.noSuchMethod(
    Invocation.setter(#socket, value),
    returnValueForMissingStub: null,
  );

  @override
  set onModerationBlocked(dynamic Function(String, String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onModerationBlocked, value),
        returnValueForMissingStub: null,
      );

  @override
  set onModerationWarning(dynamic Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onModerationWarning, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i5.ChatMessage> getMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue: <_i5.ChatMessage>[],
            returnValueForMissingStub: <_i5.ChatMessage>[],
          )
          as List<_i5.ChatMessage>);

  @override
  String? getTypingUser(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getTypingUser, [chatId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void clearData() => super.noSuchMethod(
    Invocation.method(#clearData, []),
    returnValueForMissingStub: null,
  );

  @override
  void markChatAsRead(String? chatId) => super.noSuchMethod(
    Invocation.method(#markChatAsRead, [chatId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> fetchInbox() =>
      (super.noSuchMethod(
            Invocation.method(#fetchInbox, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMessages, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> createGroup(
    String? name,
    _i7.File? image,
    List<_i8.User>? members,
    bool? allowInvites,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [
              name,
              image,
              members,
              allowInvites,
            ]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> leaveGroup(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGroup, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#clearChat, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessage(String? chatId, String? msgId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [chatId, msgId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void connectSocket(String? token, String? myUserId) => super.noSuchMethod(
    Invocation.method(#connectSocket, [token, myUserId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> deleteConversation(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void sendTyping(String? chatId, bool? isTyping) => super.noSuchMethod(
    Invocation.method(#sendTyping, [chatId, isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage(
    String? chatId,
    String? text,
    String? myUserId, {
    String? myName,
    String? myAvatar,
    String? replyToId,
  }) => super.noSuchMethod(
    Invocation.method(
      #sendMessage,
      [chatId, text, myUserId],
      {#myName: myName, #myAvatar: myAvatar, #replyToId: replyToId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i10.AuthProvider {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get needsPasswordSet =>
      (super.noSuchMethod(
            Invocation.getter(#needsPasswordSet),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String> get blockedUserIds =>
      (super.noSuchMethod(
            Invocation.getter(#blockedUserIds),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> loadBlockedUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#loadBlockedUserIds, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void updateUser(_i8.User? newUser) => super.noSuchMethod(
    Invocation.method(#updateUser, [newUser]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String?> getFreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFreshToken, []),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> register(
    String? username,
    String? displayName,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              username,
              displayName,
              email,
              password,
            ]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, dynamic>> attemptLogin(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#attemptLogin, [email, password]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<String?> verifyPinLogin(String? tempId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPinLogin, [tempId, pin]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> setPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setPin, [pin]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> removePin(String? currentPin) =>
      (super.noSuchMethod(
            Invocation.method(#removePin, [currentPin]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> resetPinByOtp(
    String? email,
    String? otp,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPinByOtp, [email, otp, newPin]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> setPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#setPassword, [password]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> completePasswordSetup() =>
      (super.noSuchMethod(
            Invocation.method(#completePasswordSetup, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> sendResetCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetCode, [email]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> verifyResetCode(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [email, code]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> resetPasswordFinish(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordFinish, [email, code, newPassword]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> toggleModeration(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleModeration, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> performLogout() =>
      (super.noSuchMethod(
            Invocation.method(#performLogout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i11.NavigatorObserver {
  @override
  void didPush(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i11.Route<dynamic>? route, _i11.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i11.Route<dynamic>? newRoute,
    _i11.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i11.Route<dynamic>? topRoute,
    _i11.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
